# Generated by Django 5.2.8 on 2025-11-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rights', models.CharField(default='new company', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=100)),
                ('GPA', models.CharField(max_length=100)),
                ('Upload_Resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('Bio', models.TextField(max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('rights', models.CharField(default='User', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=100)),
                ('positionDescription', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('internshipType', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=100)),
                ('positionsAvailable', models.IntegerField(default=1)),
                ('educationLevel', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=200)),
                ('preferredSkills', models.CharField(max_length=200)),
                ('applicationDeadline', models.DateField()),
                ('howToApply', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhone', models.CharField(max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('TechnicalSkills', models.CharField(max_length=200)),
                ('InternshipType', models.CharField(max_length=100)),
                ('PreferredDuration', models.CharField(max_length=100)),
                ('EarliestStartDate', models.DateField()),
                ('CoverLetter', models.TextField()),
                ('Status', models.CharField(default='pending', max_length=100)),
                ('internship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
