# Generated by Django 5.2.8 on 2025-11-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_applications_rejection_reason_internship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='interview_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='verification_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
