# Generated by Django 5.2.8 on 2025-11-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_applications_interview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Internship Project', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_file', models.FileField(blank=True, null=True, upload_to='project_docs/company/')),
                ('student_file', models.FileField(blank=True, null=True, upload_to='project_docs/student/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myapp.applications')),
            ],
        ),
    ]
