# Generated by Django 5.2.8 on 2025-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_projectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
