# Generated by Django 5.2.8 on 2025-11-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_applications_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='department',
            field=models.CharField(choices=[('Software', 'Software Development'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Engineering', 'Engineering'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.CreateModel(
            name='SavedInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
            options={
                'unique_together': {('student', 'internship')},
            },
        ),
    ]
